### PR TITLE
Changing to using the new AssemblyContext + Configuration + Booting

### PR DESCRIPTION
**Pull request by einari**

### CODE REVIEW

**Review by woksin — APPROVED** [review]

**Comment by woksin** [comment]
Specs are not building, @einari

**Comment by einari** [comment]
Will look into it later today. Let's not pull this in until then :)

**Comment by einari** [comment]
This is now ready to be reviewed @woksin

**Review by woksin — APPROVED** [review]
Looks good

**Comment by woksin** [comment]
But it's still failing on the restore stage, @einari

**Comment by einari** [comment]
Green and good

**Pull request merged**
